version: '3'

services:
  app:
    build: .docker/app
    container_name: app
    entrypoint: dockerize -template ./.docker/app/.env:.env  -wait tcp://db:3306 -timeout 40s ./.docker/app/start.sh
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    volumes:
      - .:/var/www
    depends_on:
      - db
      - redis
    networks:
      - app-network

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    depends_on:
      - app
    networks:
      - app-network

  db:
    build: .docker/mysql
    command: --innodb-use-native-aio=0 --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    networks:
      - app-network

  redis:
    image:  redis:alpine
    container_name: redis
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
